/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LmiAmbulanceWlList {
    }
}
declare global {
    interface HTMLLmiAmbulanceWlListElement extends Components.LmiAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLLmiAmbulanceWlListElement: {
        prototype: HTMLLmiAmbulanceWlListElement;
        new (): HTMLLmiAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "lmi-ambulance-wl-list": HTMLLmiAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface LmiAmbulanceWlList {
    }
    interface IntrinsicElements {
        "lmi-ambulance-wl-list": LmiAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lmi-ambulance-wl-list": LocalJSX.LmiAmbulanceWlList & JSXBase.HTMLAttributes<HTMLLmiAmbulanceWlListElement>;
        }
    }
}
